export const levels = [
    // --- Dificultad Baja (Niveles 1-10) ---
    {
        id: 1, title: "Nivel 1", passingScore: 0.6,
        questions: [
            { question: { es: "¿Qué planeta es conocido como el 'Planeta Rojo'?", en: "Which planet is known as the 'Red Planet'?" }, options: { es: ["Venus", "Marte", "Júpiter", "Saturno"], en: ["Venus", "Mars", "Jupiter", "Saturn"] }, correctAnswer: { es: "Marte", en: "Mars" } },
            { question: { es: "¿Cuál es el proceso por el cual las plantas fabrican su propio alimento?", en: "What is the process by which plants make their own food?" }, options: { es: ["Respiración", "Fotosíntesis", "Digestión", "Absorción"], en: ["Respiration", "Photosynthesis", "Digestion", "Absorption"] }, correctAnswer: { es: "Fotosíntesis", en: "Photosynthesis" } },
            { question: { es: "El agua en estado sólido se llama...", en: "Water in a solid state is called..." }, options: { es: ["Vapor", "Líquido", "Hielo", "Gas"], en: ["Vapor", "Liquid", "Ice", "Gas"] }, correctAnswer: { es: "Hielo", en: "Ice" } },
            { question: { es: "El centro de nuestro sistema solar es...", en: "The center of our solar system is..." }, options: { es: ["La Tierra", "La Luna", "Júpiter", "El Sol"], en: ["The Earth", "The Moon", "Jupiter", "The Sun"] }, correctAnswer: { es: "El Sol", en: "The Sun" } },
            { question: { es: "¿Qué parte de la planta absorbe agua y nutrientes del suelo?", en: "Which part of the plant absorbs water and nutrients from the soil?" }, options: { es: ["Hoja", "Flor", "Tallo", "Raíz"], en: ["Leaf", "Flower", "Stem", "Root"] }, correctAnswer: { es: "Raíz", en: "Root" } }
        ]
    },
    {
        id: 2, title: "Nivel 2", passingScore: 0.6,
        questions: [
            { question: { es: "¿Cuál es el órgano principal del sistema respiratorio?", en: "What is the main organ of the respiratory system?" }, options: { es: ["Corazón", "Cerebro", "Pulmones", "Estómago"], en: ["Heart", "Brain", "Lungs", "Stomach"] }, correctAnswer: { es: "Pulmones", en: "Lungs" } },
            { question: { es: "El ciclo del agua incluye evaporación, condensación y...", en: "The water cycle includes evaporation, condensation, and..." }, options: { es: ["Precipitación", "Filtración", "Erosión", "Congelación"], en: ["Precipitation", "Filtration", "Erosion", "Freezing"] }, correctAnswer: { es: "Precipitación", en: "Precipitation" } },
            { question: { es: "¿Qué gas necesitamos los humanos para respirar?", en: "What gas do humans need to breathe?" }, options: { es: ["Nitrógeno", "Dióxido de Carbono", "Oxígeno", "Helio"], en: ["Nitrogen", "Carbon Dioxide", "Oxygen", "Helium"] }, correctAnswer: { es: "Oxígeno", en: "Oxygen" } },
            { question: { es: "Un animal que come solo plantas se llama...", en: "An animal that only eats plants is called a..." }, options: { es: ["Carnívoro", "Omnívoro", "Herbívoro", "Insectívoro"], en: ["Carnivore", "Omnivore", "Herbivore", "Insectivore"] }, correctAnswer: { es: "Herbívoro", en: "Herbivore" } },
            { question: { es: "¿Cuál es el satélite natural de la Tierra?", en: "What is Earth's natural satellite?" }, options: { es: ["El Sol", "Marte", "La Luna", "Estrella Polar"], en: ["The Sun", "Mars", "The Moon", "North Star"] }, correctAnswer: { es: "La Luna", en: "The Moon" } }
        ]
    },
    {
        id: 3, title: "Nivel 3", passingScore: 0.7,
        questions: [
            { question: { es: "La fuerza que nos mantiene pegados al suelo se llama...", en: "The force that keeps us attached to the ground is called..." }, options: { es: ["Magnetismo", "Fricción", "Gravedad", "Electricidad"], en: ["Magnetism", "Friction", "Gravity", "Electricity"] }, correctAnswer: { es: "Gravedad", en: "Gravity" } },
            { question: { es: "El esqueleto humano está formado por...", en: "The human skeleton is made of..." }, options: { es: ["Músculos", "Huesos", "Piel", "Venas"], en: ["Muscles", "Bones", "Skin", "Veins"] }, correctAnswer: { es: "Huesos", en: "Bones" } },
            { question: { es: "Los tres estados de la materia son sólido, líquido y...", en: "The three states of matter are solid, liquid, and..." }, options: { es: ["Plasma", "Gel", "Gaseoso", "Espuma"], en: ["Plasma", "Gel", "Gaseous", "Foam"] }, correctAnswer: { es: "Gaseoso", en: "Gaseous" } },
            { question: { es: "¿Qué animal es un mamífero y puede volar?", en: "Which animal is a mammal and can fly?" }, options: { es: ["Pájaro", "Insecto", "Murciélago", "Pez volador"], en: ["Bird", "Insect", "Bat", "Flying fish"] }, correctAnswer: { es: "Murciélago", en: "Bat" } },
            { question: { es: "¿Cuál es el símbolo químico del agua?", en: "What is the chemical symbol for water?" }, options: { es: ["O2", "CO2", "H2O", "NaCl"], en: ["O2", "CO2", "H2O", "NaCl"] }, correctAnswer: { es: "H2O", en: "H2O" } }
        ]
    },
    {
        id: 4, title: "Nivel 4", passingScore: 0.7,
        questions: [
            { question: { es: "¿Qué tipo de energía obtenemos del sol?", en: "What type of energy do we get from the sun?" }, options: { es: ["Eólica", "Geotérmica", "Solar", "Hidráulica"], en: ["Wind", "Geothermal", "Solar", "Hydraulic"] }, correctAnswer: { es: "Solar", en: "Solar" } },
            { question: { es: "Un animal que come tanto plantas como carne es un...", en: "An animal that eats both plants and meat is a..." }, options: { es: ["Carnívoro", "Herbívoro", "Omnívoro", "Productor"], en: ["Carnivore", "Herbivore", "Omnivore", "Producer"] }, correctAnswer: { es: "Omnívoro", en: "Omnivore" } },
            { question: { es: "¿Cuál es el hueso más largo del cuerpo humano?", en: "What is the longest bone in the human body?" }, options: { es: ["Cráneo", "Costilla", "Fémur", "Húmero"], en: ["Skull", "Rib", "Femur", "Humerus"] }, correctAnswer: { es: "Fémur", en: "Femur" } },
            { question: { es: "¿Cómo se llama el estudio de los seres vivos?", en: "What is the study of living beings called?" }, options: { es: ["Geología", "Astronomía", "Química", "Biología"], en: ["Geology", "Astronomy", "Chemistry", "Biology"] }, correctAnswer: { es: "Biología", en: "Biology" } },
            { question: { es: "¿Qué planeta es famoso por sus anillos?", en: "Which planet is famous for its rings?" }, options: { es: ["Júpiter", "Saturno", "Urano", "Neptuno"], en: ["Jupiter", "Saturn", "Uranus", "Neptune"] }, correctAnswer: { es: "Saturno", en: "Saturn" } }
        ]
    },
    {
        id: 5, title: "Nivel 5", passingScore: 0.7,
        questions: [
            { question: { es: "¿Cuál de estos es un recurso renovable?", en: "Which of these is a renewable resource?" }, options: { es: ["Petróleo", "Carbón", "Viento", "Gas Natural"], en: ["Oil", "Coal", "Wind", "Natural Gas"] }, correctAnswer: { es: "Viento", en: "Wind" } },
            { question: { es: "La capa que rodea la Tierra y la protege se llama...", en: "The layer that surrounds and protects the Earth is called the..." }, options: { es: ["Corteza", "Manto", "Atmósfera", "Núcleo"], en: ["Crust", "Mantle", "Atmosphere", "Core"] }, correctAnswer: { es: "Atmósfera", en: "Atmosphere" } },
            { question: { es: "El proceso de cambiar de líquido a gas se llama...", en: "The process of changing from liquid to gas is called..." }, options: { es: ["Fusión", "Solidificación", "Evaporación", "Condensación"], en: ["Melting", "Solidification", "Evaporation", "Condensation"] }, correctAnswer: { es: "Evaporación", en: "Evaporation" } },
            { question: { es: "¿Qué órgano bombea sangre por todo el cuerpo?", en: "Which organ pumps blood throughout the body?" }, options: { es: ["Cerebro", "Pulmón", "Corazón", "Hígado"], en: ["Brain", "Lung", "Heart", "Liver"] }, correctAnswer: { es: "Corazón", en: "Heart" } },
            { question: { es: "¿Qué tipo de animal es una rana?", en: "What type of animal is a frog?" }, options: { es: ["Reptil", "Anfibio", "Mamífero", "Pez"], en: ["Reptile", "Amphibian", "Mammal", "Fish"] }, correctAnswer: { es: "Anfibio", en: "Amphibian" } }
        ]
    },
    {
        id: 6, title: "Nivel 6", passingScore: 0.75,
        questions: [
            { question: { es: "¿Cuál es el símbolo químico del oro?", en: "What is the chemical symbol for gold?" }, options: { es: ["Ag", "Au", "O", "Fe"], en: ["Ag", "Au", "O", "Fe"] }, correctAnswer: { es: "Au", en: "Au" } },
            { question: { es: "La unidad básica de la vida es la...", en: "The basic unit of life is the..." }, options: { es: ["Molécula", "Célula", "Átomo", "Tejido"], en: ["Molecule", "Cell", "Atom", "Tissue"] }, correctAnswer: { es: "Célula", en: "Cell" } },
            { question: { es: "¿Qué científico desarrolló la teoría de la relatividad?", en: "Which scientist developed the theory of relativity?" }, options: { es: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Marie Curie"], en: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Marie Curie"] }, correctAnswer: { es: "Albert Einstein", en: "Albert Einstein" } },
            { question: { es: "El movimiento de la Tierra sobre su propio eje causa...", en: "The movement of the Earth on its own axis causes..." }, options: { es: ["Las estaciones", "El día y la noche", "Los eclipses", "Las mareas"], en: ["The seasons", "Day and night", "Eclipses", "The tides"] }, correctAnswer: { es: "El día y la noche", en: "Day and night" } },
            { question: { es: "¿Cuál es el metal más abundante en la corteza terrestre?", en: "What is the most abundant metal in the Earth's crust?" }, options: { es: ["Hierro", "Cobre", "Aluminio", "Plata"], en: ["Iron", "Copper", "Aluminum", "Silver"] }, correctAnswer: { es: "Aluminio", en: "Aluminum" } }
        ]
    },
    {
        id: 7, title: "Nivel 7", passingScore: 0.75,
        questions: [
            { question: { es: "¿Cuál es la fórmula química del dióxido de carbono?", en: "What is the chemical formula for carbon dioxide?" }, options: { es: ["CO", "H2O", "O2", "CO2"], en: ["CO", "H2O", "O2", "CO2"] }, correctAnswer: { es: "CO2", en: "CO2" } },
            { question: { es: "¿Qué tipo de estrella es el Sol?", en: "What type of star is the Sun?" }, options: { es: ["Gigante roja", "Enana blanca", "Enana amarilla", "Supernova"], en: ["Red giant", "White dwarf", "Yellow dwarf", "Supernova"] }, correctAnswer: { es: "Enana amarilla", en: "Yellow dwarf" } },
            { question: { es: "El ADN es la abreviatura de...", en: "DNA is the abbreviation for..." }, options: { es: ["Ácido desoxirribonucleico", "Ácido ribonucleico", "Doble núcleo atómico", "Datos de nuestro ancestro"], en: ["Deoxyribonucleic acid", "Ribonucleic acid", "Double atomic nucleus", "Data of our ancestor"] }, correctAnswer: { es: "Ácido desoxirribonucleico", en: "Deoxyribonucleic acid" } },
            { question: { es: "¿Cuál de estos no es un planeta enano?", en: "Which of these is not a dwarf planet?" }, options: { es: ["Ceres", "Plutón", "Europa", "Eris"], en: ["Ceres", "Pluto", "Europa", "Eris"] }, correctAnswer: { es: "Europa", en: "Europa" } },
            { question: { es: "La energía en movimiento se conoce como...", en: "Energy in motion is known as..." }, options: { es: ["Energía potencial", "Energía química", "Energía cinética", "Energía nuclear"], en: ["Potential energy", "Chemical energy", "Kinetic energy", "Nuclear energy"] }, correctAnswer: { es: "Energía cinética", en: "Kinetic energy" } }
        ]
    },
    {
        id: 8, title: "Nivel 8", passingScore: 0.8,
        questions: [
            { question: { es: "¿Qué mide un sismógrafo?", en: "What does a seismograph measure?" }, options: { es: ["La velocidad del viento", "La presión atmosférica", "La intensidad de los terremotos", "La temperatura"], en: ["Wind speed", "Atmospheric pressure", "The intensity of earthquakes", "Temperature"] }, correctAnswer: { es: "La intensidad de los terremotos", en: "The intensity of earthquakes" } },
            { question: { es: "La capa de ozono protege a la Tierra de...", en: "The ozone layer protects the Earth from..." }, options: { es: ["Meteoritos", "Radiación ultravioleta", "Viento solar", "Asteroides"], en: ["Meteorites", "Ultraviolet radiation", "Solar wind", "Asteroids"] }, correctAnswer: { es: "Radiación ultravioleta", en: "Ultraviolet radiation" } },
            { question: { es: "¿Cuál es la velocidad del sonido en el aire?", en: "What is the speed of sound in air?" }, options: { es: ["343 m/s", "1,000 m/s", "100 m/s", "3,000 km/s"], en: ["343 m/s", "1,000 m/s", "100 m/s", "3,000 km/s"] }, correctAnswer: { es: "343 m/s", en: "343 m/s" } },
            { question: { es: "¿Cómo se llama el proceso de división celular?", en: "What is the process of cell division called?" }, options: { es: ["Meiosis", "Mitosis", "Metamorfosis", "Ósmosis"], en: ["Meiosis", "Mitosis", "Metamorphosis", "Osmosis"] }, correctAnswer: { es: "Mitosis", en: "Mitosis" } },
            { question: { es: "¿Qué gas liberan las plantas durante la fotosíntesis?", en: "What gas do plants release during photosynthesis?" }, options: { es: ["Nitrógeno", "Oxígeno", "Dióxido de Carbono", "Vapor de agua"], en: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Water vapor"] }, correctAnswer: { es: "Oxígeno", en: "Oxygen" } }
        ]
    },
    {
        id: 9, title: "Nivel 9", passingScore: 0.8,
        questions: [
            { question: { es: "¿Cuál es el elemento más ligero de la tabla periódica?", en: "What is the lightest element in the periodic table?" }, options: { es: ["Helio", "Oxígeno", "Hidrógeno", "Carbono"], en: ["Helium", "Oxygen", "Hydrogen", "Carbon"] }, correctAnswer: { es: "Hidrógeno", en: "Hydrogen" } },
            { question: { es: "Un conjunto de órganos que trabajan juntos forma un...", en: "A set of organs working together forms a..." }, options: { es: ["Tejido", "Sistema", "Célula", "Organismo"], en: ["Tissue", "System", "Cell", "Organism"] }, correctAnswer: { es: "Sistema", en: "System" } },
            { question: { es: "¿Qué tipo de lente corrige la miopía?", en: "What type of lens corrects nearsightedness (myopia)?" }, options: { es: ["Convexa", "Plana", "Bifocal", "Cóncava"], en: ["Convex", "Flat", "Bifocal", "Concave"] }, correctAnswer: { es: "Cóncava", en: "Concave" } },
            { question: { es: "El estudio de los fósiles se llama...", en: "The study of fossils is called..." }, options: { es: ["Arqueología", "Paleontología", "Geología", "Antropología"], en: ["Archaeology", "Paleontology", "Geology", "Anthropology"] }, correctAnswer: { es: "Paleontología", en: "Paleontology" } },
            { question: { es: "¿Cuántos cromosomas tiene un ser humano?", en: "How many chromosomes does a human have?" }, options: { es: ["46", "23", "48", "24"], en: ["46", "23", "48", "24"] }, correctAnswer: { es: "46", en: "46" } }
        ]
    },
    {
        id: 10, title: "Nivel 10", passingScore: 0.8,
        questions: [
            { question: { es: "¿Qué es la Vía Láctea?", en: "What is the Milky Way?" }, options: { es: ["Un planeta", "Una estrella", "Una galaxia", "Un cometa"], en: ["A planet", "A star", "A galaxy", "A comet"] }, correctAnswer: { es: "Una galaxia", en: "A galaxy" } },
            { question: { es: "¿Cuál es el metal más denso?", en: "What is the densest metal?" }, options: { es: ["Plomo", "Osmio", "Oro", "Platino"], en: ["Lead", "Osmium", "Gold", "Platinum"] }, correctAnswer: { es: "Osmio", en: "Osmium" } },
            { question: { es: "La teoría del Big Bang describe el origen del...", en: "The Big Bang theory describes the origin of the..." }, options: { es: ["Universo", "Sistema Solar", "Planeta Tierra", "Ser humano"], en: ["Universe", "Solar System", "Planet Earth", "Human being"] }, correctAnswer: { es: "Universo", en: "Universe" } },
            { question: { es: "¿Cuál es la principal función de los glóbulos rojos?", en: "What is the main function of red blood cells?" }, options: { es: ["Combatir infecciones", "Transportar oxígeno", "Coagular la sangre", "Producir anticuerpos"], en: ["Fight infections", "Transport oxygen", "Clot blood", "Produce antibodies"] }, correctAnswer: { es: "Transportar oxígeno", en: "Transport oxygen" } },
            { question: { es: "¿Qué es un año luz?", en: "What is a light-year?" }, options: { es: ["Una medida de tiempo", "Una medida de velocidad", "Una medida de distancia", "Una medida de brillo"], en: ["A measure of time", "A measure of speed", "A measure of distance", "A measure of brightness"] }, correctAnswer: { es: "Una medida de distancia", en: "A measure of distance" } }
        ]
    },
    // --- Dificultad Avanzada (Niveles 11-20) ---
    {
        id: 11, title: "Nivel 11", passingScore: 0.85,
        questions: [
            { question: { es: "¿Qué ley de Newton establece que a toda acción corresponde una reacción?", en: "Which of Newton's laws states that for every action there is an equal and opposite reaction?" }, options: { es: ["Primera Ley", "Segunda Ley", "Tercera Ley", "Ley de Gravitación"], en: ["First Law", "Second Law", "Third Law", "Law of Gravitation"] }, correctAnswer: { es: "Tercera Ley", en: "Third Law" } },
            { question: { es: "La mitocondria es conocida como la 'central de energía' de la...", en: "The mitochondrion is known as the 'powerhouse' of the..." }, options: { es: ["Planta", "Célula", "Bacteria", "Estrella"], en: ["Plant", "Cell", "Bacteria", "Star"] }, correctAnswer: { es: "Célula", en: "Cell" } },
            { question: { es: "¿Cuál es el pH de una sustancia neutra?", en: "What is the pH of a neutral substance?" }, options: { es: ["0", "14", "1", "7"], en: ["0", "14", "1", "7"] }, correctAnswer: { es: "7", en: "7" } },
            { question: { es: "¿Qué tipo de roca se forma por el enfriamiento del magma?", en: "What type of rock is formed by the cooling of magma?" }, options: { es: ["Sedimentaria", "Metamórfica", "Ígnea", "Fósil"], en: ["Sedimentary", "Metamorphic", "Igneous", "Fossil"] }, correctAnswer: { es: "Ígnea", en: "Igneous" } },
            { question: { es: "El efecto invernadero es causado principalmente por un aumento de...", en: "The greenhouse effect is primarily caused by an increase in..." }, options: { es: ["Oxígeno", "Nitrógeno", "Dióxido de Carbono", "Argón"], en: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"] }, correctAnswer: { es: "Dióxido de Carbono", en: "Carbon Dioxide" } }
        ]
    },
    {
        id: 12, title: "Nivel 12", passingScore: 0.85,
        questions: [
            { question: { es: "¿Qué parte del átomo tiene carga negativa?", en: "What part of the atom has a negative charge?" }, options: { es: ["Protón", "Neutrón", "Electrón", "Núcleo"], en: ["Proton", "Neutron", "Electron", "Nucleus"] }, correctAnswer: { es: "Electrón", en: "Electron" } },
            { question: { es: "La penicilina, un famoso antibiótico, fue descubierta por...", en: "Penicillin, a famous antibiotic, was discovered by..." }, options: { es: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], en: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"] }, correctAnswer: { es: "Alexander Fleming", en: "Alexander Fleming" } },
            { question: { es: "¿Qué es la ósmosis?", en: "What is osmosis?" }, options: { es: ["Paso de soluto a través de una membrana", "Paso de solvente a través de una membrana", "División celular", "Creación de energía"], en: ["Passage of solute through a membrane", "Passage of solvent through a membrane", "Cell division", "Energy creation"] }, correctAnswer: { es: "Paso de solvente a través de una membrana", en: "Passage of solvent through a membrane" } },
            { question: { es: "¿Cuál es el planeta más grande del sistema solar?", en: "What is the largest planet in the solar system?" }, options: { es: ["Tierra", "Marte", "Júpiter", "Saturno"], en: ["Earth", "Mars", "Jupiter", "Saturn"] }, correctAnswer: { es: "Júpiter", en: "Jupiter" } },
            { question: { es: "La erosión es el desgaste de la superficie terrestre por...", en: "Erosion is the wearing away of the Earth's surface by..." }, options: { es: ["Agua y viento", "Actividad volcánica", "Terremotos", "Luz solar"], en: ["Water and wind", "Volcanic activity", "Earthquakes", "Sunlight"] }, correctAnswer: { es: "Agua y viento", en: "Water and wind" } }
        ]
    },
    {
        id: 13, title: "Nivel 13", passingScore: 0.85,
        questions: [
            { question: { es: "¿Qué es un ecosistema?", en: "What is an ecosystem?" }, options: { es: ["Una especie animal", "Un tipo de planta", "Una comunidad de seres vivos y su entorno", "Un bioma acuático"], en: ["An animal species", "A type of plant", "A community of living beings and their environment", "An aquatic biome"] }, correctAnswer: { es: "Una comunidad de seres vivos y su entorno", en: "A community of living beings and their environment" } },
            { question: { es: "La tabla periódica organiza los elementos por su...", en: "The periodic table organizes elements by their..." }, options: { es: ["Masa atómica", "Número atómico", "Color", "Densidad"], en: ["Atomic mass", "Atomic number", "Color", "Density"] }, correctAnswer: { es: "Número atómico", en: "Atomic number" } },
            { question: { es: "¿Qué es un herbívoro?", en: "What is a herbivore?" }, options: { es: ["Come carne", "Come plantas", "Come de todo", "No come"], en: ["Eats meat", "Eats plants", "Eats everything", "Doesn't eat"] }, correctAnswer: { es: "Come plantas", en: "Eats plants" } },
            { question: { es: "La Vía Láctea es una galaxia de tipo...", en: "The Milky Way is a galaxy of the type..." }, options: { es: ["Elíptica", "Irregular", "Lenticular", "Espiral"], en: ["Elliptical", "Irregular", "Lenticular", "Spiral"] }, correctAnswer: { es: "Espiral", en: "Spiral" } },
            { question: { es: "¿Qué vitamina se conoce como ácido ascórbico?", en: "Which vitamin is known as ascorbic acid?" }, options: { es: ["Vitamina A", "Vitamina B", "Vitamina C", "Vitamina D"], en: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"] }, correctAnswer: { es: "Vitamina C", en: "Vitamin C" } }
        ]
    },
    {
        id: 14, title: "Nivel 14", passingScore: 0.9,
        questions: [
            { question: { es: "¿Cuál de estos animales es un reptil?", en: "Which of these animals is a reptile?" }, options: { es: ["Rana", "Serpiente", "Salmón", "Pelícano"], en: ["Frog", "Snake", "Salmon", "Pelican"] }, correctAnswer: { es: "Serpiente", en: "Snake" } },
            { question: { es: "La ciencia que estudia el clima es la...", en: "The science that studies climate is..." }, options: { es: ["Meteorología", "Climatología", "Geografía", "Ecología"], en: ["Meteorology", "Climatology", "Geography", "Ecology"] }, correctAnswer: { es: "Climatología", en: "Climatology" } },
            { question: { es: "¿Qué es la materia?", en: "What is matter?" }, options: { es: ["Solo lo que podemos ver", "Todo lo que tiene masa y ocupa espacio", "Energía pura", "Una idea abstracta"], en: ["Only what we can see", "Anything that has mass and takes up space", "Pure energy", "An abstract idea"] }, correctAnswer: { es: "Todo lo que tiene masa y ocupa espacio", en: "Anything that has mass and takes up space" } },
            { question: { es: "La Luna refleja la luz del...", en: "The Moon reflects light from the..." }, options: { es: ["Sol", "La Tierra", "Marte", "Las estrellas"], en: ["Sun", "Earth", "Mars", "The stars"] }, correctAnswer: { es: "Sol", en: "Sun" } },
            { question: { es: "¿Cuál es el proceso opuesto a la evaporación?", en: "What is the opposite process of evaporation?" }, options: { es: ["Fusión", "Sublimación", "Condensación", "Ebullición"], en: ["Melting", "Sublimation", "Condensation", "Boiling"] }, correctAnswer: { es: "Condensación", en: "Condensation" } }
        ]
    },
    {
        id: 15, title: "Nivel 15", passingScore: 0.9,
        questions: [
            { question: { es: "¿Qué es un tsunami?", en: "What is a tsunami?" }, options: { es: ["Un tornado en el mar", "Una ola gigante causada por un terremoto submarino", "Una tormenta tropical", "Una erupción volcánica"], en: ["A tornado at sea", "A giant wave caused by an underwater earthquake", "A tropical storm", "A volcanic eruption"] }, correctAnswer: { es: "Una ola gigante causada por un terremoto submarino", en: "A giant wave caused by an underwater earthquake" } },
            { question: { es: "El estudio de los hongos se llama...", en: "The study of fungi is called..." }, options: { es: ["Botánica", "Zoología", "Micología", "Virología"], en: ["Botany", "Zoology", "Mycology", "Virology"] }, correctAnswer: { es: "Micología", en: "Mycology" } },
            { question: { es: "¿Cuál es la galaxia más cercana a la Vía Láctea?", en: "What is the closest galaxy to the Milky Way?" }, options: { es: ["Triángulo", "Andrómeda", "Sombrero", "Remolino"], en: ["Triangulum", "Andromeda", "Sombrero", "Whirlpool"] }, correctAnswer: { es: "Andrómeda", en: "Andromeda" } },
            { question: { es: "¿Qué parte de la célula contiene la información genética?", en: "What part of the cell contains the genetic information?" }, options: { es: ["Membrana", "Citoplasma", "Núcleo", "Mitocondria"], en: ["Membrane", "Cytoplasm", "Nucleus", "Mitochondrion"] }, correctAnswer: { es: "Núcleo", en: "Nucleus" } },
            { question: { es: "La escala de Richter mide la magnitud de...", en: "The Richter scale measures the magnitude of..." }, options: { es: ["Huracanes", "Tornados", "Terremotos", "Erupciones"], en: ["Hurricanes", "Tornadoes", "Earthquakes", "Eruptions"] }, correctAnswer: { es: "Terremotos", en: "Earthquakes" } }
        ]
    },
    {
        id: 16, title: "Nivel 16", passingScore: 0.9,
        questions: [
            { question: { es: "¿Qué es la biotecnología?", en: "What is biotechnology?" }, options: { es: ["El estudio de los robots", "El uso de organismos vivos para crear productos", "La clonación de animales", "La creación de vida artificial"], en: ["The study of robots", "The use of living organisms to create products", "The cloning of animals", "The creation of artificial life"] }, correctAnswer: { es: "El uso de organismos vivos para crear productos", en: "The use of living organisms to create products" } },
            { question: { es: "¿Qué es la materia oscura?", en: "What is dark matter?" }, options: { es: ["Materia que no emite luz", "El espacio entre estrellas", "Agujeros negros", "Materia quemada"], en: ["Matter that does not emit light", "The space between stars", "Black holes", "Burnt matter"] }, correctAnswer: { es: "Materia que no emite luz", en: "Matter that does not emit light" } },
            { question: { es: "¿Cuál es el ácido presente en el estómago?", en: "What is the acid present in the stomach?" }, options: { es: ["Ácido sulfúrico", "Ácido acético", "Ácido clorhídrico", "Ácido cítrico"], en: ["Sulfuric acid", "Acetic acid", "Hydrochloric acid", "Citric acid"] }, correctAnswer: { es: "Ácido clorhídrico", en: "Hydrochloric acid" } },
            { question: { es: "La fisión nuclear es el proceso de...", en: "Nuclear fission is the process of..." }, options: { es: ["Unir núcleos atómicos", "Dividir un núcleo atómico pesado", "Crear nuevos elementos", "Generar electricidad estática"], en: ["Joining atomic nuclei", "Splitting a heavy atomic nucleus", "Creating new elements", "Generating static electricity"] }, correctAnswer: { es: "Dividir un núcleo atómico pesado", en: "Splitting a heavy atomic nucleus" } },
            { question: { es: "¿Qué es la penicilina?", en: "What is penicillin?" }, options: { es: ["Un virus", "Una bacteria", "Un hongo", "Un antibiótico"], en: ["A virus", "A bacterium", "A fungus", "An antibiotic"] }, correctAnswer: { es: "Un antibiótico", en: "An antibiotic" } }
        ]
    },
    {
        id: 17, title: "Nivel 17", passingScore: 0.95,
        questions: [
            { question: { es: "El efecto Doppler explica el cambio de... de una onda.", en: "The Doppler effect explains the change in... of a wave." }, options: { es: ["Frecuencia", "Amplitud", "Velocidad", "Longitud"], en: ["Frequency", "Amplitude", "Speed", "Length"] }, correctAnswer: { es: "Frecuencia", en: "Frequency" } },
            { question: { es: "¿Qué es la entropía?", en: "What is entropy?" }, options: { es: ["Una medida del orden", "Una medida del desorden", "Energía almacenada", "Una fuerza fundamental"], en: ["A measure of order", "A measure of disorder", "Stored energy", "A fundamental force"] }, correctAnswer: { es: "Una medida del desorden", en: "A measure of disorder" } },
            { question: { es: "Los quarks son partículas fundamentales que componen...", en: "Quarks are fundamental particles that make up..." }, options: { es: ["Electrones", "Protones y neutrones", "Fotones", "Átomos"], en: ["Electrons", "Protons and neutrons", "Photons", "Atoms"] }, correctAnswer: { es: "Protones y neutrones", en: "Protons and neutrons" } },
            { question: { es: "¿Qué es un prión?", en: "What is a prion?" }, options: { es: ["Un virus", "Una bacteria", "Una proteína mal plegada", "Un tipo de hongo"], en: ["A virus", "A bacterium", "A misfolded protein", "A type of fungus"] }, correctAnswer: { es: "Una proteína mal plegada", en: "A misfolded protein" } },
            { question: { es: "La antimateria está compuesta por...", en: "Antimatter is composed of..." }, options: { es: ["Energía oscura", "Antipartículas", "Materia exótica", "Neutrinos"], en: ["Dark energy", "Antiparticles", "Exotic matter", "Neutrinos"] }, correctAnswer: { es: "Antipartículas", en: "Antiparticles" } }
        ]
    },
    {
        id: 18, title: "Nivel 18", passingScore: 0.95,
        questions: [
            { question: { es: "¿Qué es la superconductividad?", en: "What is superconductivity?" }, options: { es: ["Resistencia eléctrica infinita", "Resistencia eléctrica cero", "Alta conductividad térmica", "Magnetismo perfecto"], en: ["Infinite electrical resistance", "Zero electrical resistance", "High thermal conductivity", "Perfect magnetism"] }, correctAnswer: { es: "Resistencia eléctrica cero", en: "Zero electrical resistance" } },
            { question: { es: "El Bosón de Higgs es una partícula asociada con...", en: "The Higgs Boson is a particle associated with..." }, options: { es: ["La gravedad", "La masa", "La luz", "El magnetismo"], en: ["Gravity", "Mass", "Light", "Magnetism"] }, correctAnswer: { es: "La masa", en: "Mass" } },
            { question: { es: "¿Qué es la edición genética CRISPR?", en: "What is CRISPR gene editing?" }, options: { es: ["Una técnica de clonación", "Una herramienta para cortar y pegar ADN", "Un tipo de terapia génica", "Un método de secuenciación"], en: ["A cloning technique", "A tool for cutting and pasting DNA", "A type of gene therapy", "A sequencing method"] }, correctAnswer: { es: "Una herramienta para cortar y pegar ADN", en: "A tool for cutting and pasting DNA" } },
            { question: { es: "Un agujero negro es una región del espacio con una gravedad tan fuerte que ni siquiera... puede escapar.", en: "A black hole is a region of space with gravity so strong that not even... can escape." }, options: { es: ["La materia", "El sonido", "La luz", "El tiempo"], en: ["Matter", "Sound", "Light", "Time"] }, correctAnswer: { es: "La luz", en: "Light" } },
            { question: { es: "La fotosíntesis artificial busca imitar a las plantas para producir...", en: "Artificial photosynthesis seeks to imitate plants to produce..." }, options: { es: ["Agua", "Oxígeno", "Combustible solar", "Electricidad"], en: ["Water", "Oxygen", "Solar fuel", "Electricity"] }, correctAnswer: { es: "Combustible solar", en: "Solar fuel" } }
        ]
    },
    {
        id: 19, title: "Nivel 19", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es la computación cuántica?", en: "What is quantum computing?" }, options: { es: ["Computación ultrarrápida", "Uso de cúbits para procesar información", "Inteligencia artificial avanzada", "Simulación del cerebro humano"], en: ["Ultra-fast computing", "Using qubits to process information", "Advanced artificial intelligence", "Simulating the human brain"] }, correctAnswer: { es: "Uso de cúbits para procesar información", en: "Using qubits to process information" } },
            { question: { es: "El entrelazamiento cuántico es un fenómeno donde dos partículas están...", en: "Quantum entanglement is a phenomenon where two particles are..." }, options: { es: ["Unidas físicamente", "Conectadas instantáneamente a distancia", "En el mismo estado cuántico", "Vibrando a la misma frecuencia"], en: ["Physically joined", "Instantly connected at a distance", "In the same quantum state", "Vibrating at the same frequency"] }, correctAnswer: { es: "Conectadas instantáneamente a distancia", en: "Instantly connected at a distance" } },
            { question: { es: "¿Qué es la teoría de cuerdas?", en: "What is string theory?" }, options: { es: ["Una teoría sobre la música", "Un modelo que describe partículas como cuerdas vibrantes", "Una teoría de la relatividad", "Un concepto de la informática"], en: ["A theory about music", "A model that describes particles as vibrating strings", "A theory of relativity", "A computer science concept"] }, correctAnswer: { es: "Un modelo que describe partículas como cuerdas vibrantes", en: "A model that describes particles as vibrating strings" } },
            { question: { es: "La fusión nuclear, la energía de las estrellas, consiste en...", en: "Nuclear fusion, the energy of stars, consists of..." }, options: { es: ["Dividir átomos", "Unir átomos ligeros para formar uno más pesado", "Quemar hidrógeno", "Crear antimateria"], en: ["Splitting atoms", "Joining light atoms to form a heavier one", "Burning hydrogen", "Creating antimatter"] }, correctAnswer: { es: "Unir átomos ligeros para formar uno más pesado", en: "Joining light atoms to form a heavier one" } },
            { question: { es: "¿Qué son los extremófilos?", en: "What are extremophiles?" }, options: { es: ["Animales muy grandes", "Organismos que viven en condiciones extremas", "Plantas venenosas", "Bacterias de otros planetas"], en: ["Very large animals", "Organisms that live in extreme conditions", "Poisonous plants", "Bacteria from other planets"] }, correctAnswer: { es: "Organismos que viven en condiciones extremas", en: "Organisms that live in extreme conditions" } }
        ]
    },
    {
        id: 20, title: "Nivel 20", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es la singularidad en el contexto de un agujero negro?", en: "What is the singularity in the context of a black hole?" }, options: { es: ["El borde del agujero negro", "Un punto de densidad infinita en su centro", "La radiación que emite", "Una galaxia cercana"], en: ["The edge of the black hole", "A point of infinite density at its center", "The radiation it emits", "A nearby galaxy"] }, correctAnswer: { es: "Un punto de densidad infinita en su centro", en: "A point of infinite density at its center" } },
            { question: { es: "La 'materia extraña' es una forma hipotética de materia compuesta por...", en: "'Strange matter' is a hypothetical form of matter composed of..." }, options: { es: ["Quarks extraños", "Antimateria", "Materia oscura", "Neutrones"], en: ["Strange quarks", "Antimatter", "Dark matter", "Neutrons"] }, correctAnswer: { es: "Quarks extraños", en: "Strange quarks" } },
            { question: { es: "¿Qué es la panspermia?", en: "What is panspermia?" }, options: { es: ["Una enfermedad espacial", "La teoría de que la vida existe en todo el universo", "La creación de vida en laboratorio", "Un tipo de estrella"], en: ["A space disease", "The theory that life exists throughout the universe", "The creation of life in a lab", "A type of star"] }, correctAnswer: { es: "La teoría de que la vida existe en todo el universo", en: "The theory that life exists throughout the universe" } },
            { question: { es: "El principio de incertidumbre de Heisenberg establece que no se puede conocer con precisión simultáneamente...", en: "Heisenberg's uncertainty principle states that one cannot simultaneously know with precision..." }, options: { es: ["La masa y la velocidad de una partícula", "La posición y el momento de una partícula", "La energía y el tiempo de un evento", "La carga y el espín de un electrón"], en: ["The mass and velocity of a particle", "The position and momentum of a particle", "The energy and time of an event", "The charge and spin of an electron"] }, correctAnswer: { es: "La posición y el momento de una partícula", en: "The position and momentum of a particle" } },
            { question: { es: "¿Qué es un 'motor de Alcubierre'?", en: "What is an 'Alcubierre drive'?" }, options: { es: ["Un motor de cohete", "Un concepto teórico para viajar más rápido que la luz", "Un tipo de motor de iones", "Un generador de agujeros de gusano"], en: ["A rocket engine", "A theoretical concept for faster-than-light travel", "A type of ion engine", "A wormhole generator"] }, correctAnswer: { es: "Un concepto teórico para viajar más rápido que la luz", en: "A theoretical concept for faster-than-light travel" } }
        ]
    },
    // --- Dificultad Experto (Niveles 21-30) ---
    {
        id: 21, title: "Nivel 21", passingScore: 1.0,
        questions: [
            { question: { es: "La refracción es el cambio de... de una onda al pasar a otro medio.", en: "Refraction is the change in... of a wave when passing to another medium." }, options: { es: ["Dirección", "Frecuencia", "Amplitud", "Color"], en: ["Direction", "Frequency", "Amplitude", "Color"] }, correctAnswer: { es: "Dirección", en: "Direction" } },
            { question: { es: "¿Qué es un isótopo?", en: "What is an isotope?" }, options: { es: ["Un átomo con diferente número de electrones", "Un átomo con diferente número de protones", "Un átomo con diferente número de neutrones", "Un átomo de otro elemento"], en: ["An atom with a different number of electrons", "An atom with a different number of protons", "An atom with a different number of neutrons", "An atom of another element"] }, correctAnswer: { es: "Un átomo con diferente número de neutrones", en: "An atom with a different number of neutrons" } },
            { question: { es: "La Tercera Ley de la Termodinámica se relaciona con el concepto de...", en: "The Third Law of Thermodynamics is related to the concept of..." }, options: { es: ["Cero absoluto", "Energía perpetua", "Entropía máxima", "Equilibrio térmico"], en: ["Absolute zero", "Perpetual energy", "Maximum entropy", "Thermal equilibrium"] }, correctAnswer: { es: "Cero absoluto", en: "Absolute zero" } },
            { question: { es: "¿Qué es la epigenética?", en: "What is epigenetics?" }, options: { es: ["El estudio de genes antiguos", "Cambios hereditarios que no alteran la secuencia de ADN", "La manipulación de genes", "La creación de nuevas especies"], en: ["The study of ancient genes", "Heritable changes that do not alter the DNA sequence", "The manipulation of genes", "The creation of new species"] }, correctAnswer: { es: "Cambios hereditarios que no alteran la secuencia de ADN", en: "Heritable changes that do not alter the DNA sequence" } },
            { question: { es: "La magnetohidrodinámica estudia la dinámica de...", en: "Magnetohydrodynamics studies the dynamics of..." }, options: { es: ["Fluidos magnéticos", "Fluidos eléctricamente conductores", "Gases ionizados", "Cristales líquidos"], en: ["Magnetic fluids", "Electrically conducting fluids", "Ionized gases", "Liquid crystals"] }, correctAnswer: { es: "Fluidos eléctricamente conductores", en: "Electrically conducting fluids" } }
        ]
    },
    {
        id: 22, title: "Nivel 22", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es un punto de Lagrange en astronomía?", en: "What is a Lagrange point in astronomy?" }, options: { es: ["Un punto de alta gravedad", "Un punto donde las fuerzas gravitacionales se equilibran", "Una órbita estable para satélites", "El centro de una galaxia"], en: ["A point of high gravity", "A point where gravitational forces balance", "A stable orbit for satellites", "The center of a galaxy"] }, correctAnswer: { es: "Un punto donde las fuerzas gravitacionales se equilibran", en: "A point where gravitational forces balance" } },
            { question: { es: "El 'efecto túnel' es un fenómeno de la mecánica...", en: "The 'tunnel effect' is a phenomenon of... mechanics." }, options: { es: ["Clásica", "Relativista", "Cuántica", "Celeste"], en: ["Classical", "Relativistic", "Quantum", "Celestial"] }, correctAnswer: { es: "Cuántica", en: "Quantum" } },
            { question: { es: "¿Qué es un ciclo de Krebs?", en: "What is a Krebs cycle?" }, options: { es: ["Un ciclo orbital", "Una ruta metabólica en la respiración celular", "Un ciclo climático", "Un modelo matemático"], en: ["An orbital cycle", "A metabolic pathway in cellular respiration", "A climatic cycle", "A mathematical model"] }, correctAnswer: { es: "Una ruta metabólica en la respiración celular", en: "A metabolic pathway in cellular respiration" } },
            { question: { es: "¿Qué es un 'ferrofluido'?", en: "What is a 'ferrofluid'?" }, options: { es: ["Un gas magnético", "Un metal líquido", "Un líquido que se magnetiza fuertemente", "Un plasma frío"], en: ["A magnetic gas", "A liquid metal", "A liquid that becomes strongly magnetized", "A cold plasma"] }, correctAnswer: { es: "Un líquido que se magnetiza fuertemente", en: "A liquid that becomes strongly magnetized" } },
            { question: { es: "La 'hipótesis de la Tierra rara' sugiere que la vida compleja en el universo es...", en: "The 'Rare Earth hypothesis' suggests that complex life in the universe is..." }, options: { es: ["Muy común", "Extremadamente rara", "Imposible", "Artificial"], en: ["Very common", "Extremely rare", "Impossible", "Artificial"] }, correctAnswer: { es: "Extremadamente rara", en: "Extremely rare" } }
        ]
    },
    {
        id: 23, title: "Nivel 23", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué mide la constante de Hubble?", en: "What does the Hubble constant measure?" }, options: { es: ["La edad del universo", "La velocidad de expansión del universo", "La distancia a las galaxias", "La temperatura del fondo cósmico"], en: ["The age of the universe", "The expansion rate of the universe", "The distance to galaxies", "The temperature of the cosmic background"] }, correctAnswer: { es: "La velocidad de expansión del universo", en: "The expansion rate of the universe" } },
            { question: { es: "La 'paradoja del gato de Schrödinger' es un experimento mental sobre...", en: "Schrödinger's cat paradox is a thought experiment about..." }, options: { es: ["Viaje en el tiempo", "La superposición cuántica", "Agujeros negros", "La relatividad"], en: ["Time travel", "Quantum superposition", "Black holes", "Relativity"] }, correctAnswer: { es: "La superposición cuántica", en: "Quantum superposition" } },
            { question: { es: "¿Qué son los tardígrados (osos de agua)?", en: "What are tardigrades (water bears)?" }, options: { es: ["Insectos acuáticos", "Crustáceos", "Microorganismos extremófilos", "Larvas de anfibios"], en: ["Aquatic insects", "Crustaceans", "Extremophile microorganisms", "Amphibian larvae"] }, correctAnswer: { es: "Microorganismos extremófilos", en: "Extremophile microorganisms" } },
            { question: { es: "El 'horizonte de sucesos' es el límite de un...", en: "The 'event horizon' is the boundary of a..." }, options: { es: ["Agujero negro", "Estrella de neutrones", "Quásar", "Púlsar"], en: ["Black hole", "Neutron star", "Quasar", "Pulsar"] }, correctAnswer: { es: "Agujero negro", en: "Black hole" } },
            { question: { es: "¿Qué es la 'sonoluminiscencia'?", en: "What is 'sonoluminescence'?" }, options: { es: ["Luz producida por el sonido", "Sonido producido por la luz", "Bioluminiscencia", "Fosforescencia"], en: ["Light produced by sound", "Sound produced by light", "Bioluminescence", "Phosphorescence"] }, correctAnswer: { es: "Luz producida por el sonido", en: "Light produced by sound" } }
        ]
    },
    {
        id: 24, title: "Nivel 24", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué describe la Ecuación de Drake?", en: "What does the Drake Equation describe?" }, options: { es: ["La probabilidad de vida extraterrestre inteligente", "La órbita de los planetas", "La formación de estrellas", "La expansión del universo"], en: ["The probability of intelligent extraterrestrial life", "The orbit of planets", "The formation of stars", "The expansion of the universe"] }, correctAnswer: { es: "La probabilidad de vida extraterrestre inteligente", en: "The probability of intelligent extraterrestrial life" } },
            { question: { es: "La cromodinámica cuántica es la teoría que describe...", en: "Quantum chromodynamics is the theory that describes..." }, options: { es: ["La fuerza electromagnética", "La fuerza nuclear débil", "La fuerza nuclear fuerte", "La gravedad cuántica"], en: ["The electromagnetic force", "The weak nuclear force", "The strong nuclear force", "Quantum gravity"] }, correctAnswer: { es: "La fuerza nuclear fuerte", en: "The strong nuclear force" } },
            { question: { es: "¿Qué es un 'aerogel'?", en: "What is an 'aerogel'?" }, options: { es: ["Un gas solidificado", "El material sólido menos denso", "Una espuma metálica", "Un polímero transparente"], en: ["A solidified gas", "The least dense solid material", "A metallic foam", "A transparent polymer"] }, correctAnswer: { es: "El material sólido menos denso", en: "The least dense solid material" } },
            { question: { es: "La 'radiación de Cherenkov' es luz emitida cuando una partícula cargada viaja a través de un medio...", en: "Cherenkov radiation is light emitted when a charged particle travels through a medium..." }, options: { es: ["Más rápido que el sonido", "Más rápido que la luz en ese medio", "En el vacío", "A velocidad constante"], en: ["Faster than sound", "Faster than light in that medium", "In a vacuum", "At a constant speed"] }, correctAnswer: { es: "Más rápido que la luz en ese medio", en: "Faster than light in that medium" } },
            { question: { es: "La reacción de Maillard es responsable del... de los alimentos cocinados.", en: "The Maillard reaction is responsible for the... of cooked foods." }, options: { es: ["Sabor y color", "Aroma", "Textura", "Nutrientes"], en: ["Flavor and color", "Aroma", "Texture", "Nutrients"] }, correctAnswer: { es: "Sabor y color", en: "Flavor and color" } }
        ]
    },
    {
        id: 25, title: "Nivel 25", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es la 'superfluidez'?", en: "What is 'superfluidity'?" }, options: { es: ["Un líquido sin viscosidad", "Un gas sin resistencia", "Un sólido ultradenso", "Un plasma superconductor"], en: ["A liquid with no viscosity", "A gas with no resistance", "An ultra-dense solid", "A superconducting plasma"] }, correctAnswer: { es: "Un líquido sin viscosidad", en: "A liquid with no viscosity" } },
            { question: { es: "La 'esfera de Dyson' es una megaestructura hipotética construida alrededor de...", en: "A 'Dyson sphere' is a hypothetical megastructure built around..." }, options: { es: ["Un planeta", "Una estrella", "Una galaxia", "Un agujero negro"], en: ["A planet", "A star", "A galaxy", "A black hole"] }, correctAnswer: { es: "Una estrella", en: "A star" } },
            { question: { es: "¿Qué es la 'memoria del agua'?", en: "What is 'water memory'?" }, options: { es: ["Una propiedad cuántica", "Una idea pseudocientífica", "Un fenómeno químico", "Un efecto biológico"], en: ["A quantum property", "A pseudoscientific idea", "A chemical phenomenon", "A biological effect"] }, correctAnswer: { es: "Una idea pseudocientífica", en: "A pseudoscientific idea" } },
            { question: { es: "El 'Gran Atractor' es una anomalía gravitacional en...", en: "The 'Great Attractor' is a gravitational anomaly in..." }, options: { es: ["Nuestra galaxia", "El espacio intergaláctico", "El cinturón de Kuiper", "La nube de Oort"], en: ["Our galaxy", "Intergalactic space", "The Kuiper Belt", "The Oort Cloud"] }, correctAnswer: { es: "El espacio intergaláctico", en: "Intergalactic space" } },
            { question: { es: "¿Qué es la 'retrocausalidad' en física?", en: "What is 'retrocausality' in physics?" }, options: { es: ["Causar un efecto en el pasado", "Un bucle temporal", "La inversión del tiempo", "Un efecto sin causa"], en: ["Causing an effect in the past", "A time loop", "The reversal of time", "An effect without a cause"] }, correctAnswer: { es: "Causar un efecto en el pasado", en: "Causing an effect in the past" } }
        ]
    },
    {
        id: 26, title: "Nivel 26", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es un 'condensado de Bose-Einstein'?", en: "What is a 'Bose-Einstein condensate'?" }, options: { es: ["Un estado de la materia a altas temperaturas", "Un estado de la materia cerca del cero absoluto", "Un tipo de cristal", "Un gas ionizado"], en: ["A state of matter at high temperatures", "A state of matter near absolute zero", "A type of crystal", "An ionized gas"] }, correctAnswer: { es: "Un estado de la materia cerca del cero absoluto", en: "A state of matter near absolute zero" } },
            { question: { es: "El 'problema de la medida' es una cuestión fundamental en...", en: "The 'measurement problem' is a fundamental issue in..." }, options: { es: ["Mecánica cuántica", "Relatividad general", "Termodinámica", "Óptica"], en: ["Quantum mechanics", "General relativity", "Thermodynamics", "Optics"] }, correctAnswer: { es: "Mecánica cuántica", en: "Quantum mechanics" } },
            { question: { es: "¿Qué es un 'magnetar'?", en: "What is a 'magnetar'?" }, options: { es: ["Un tipo de quásar", "Una estrella de neutrones con un campo magnético extremadamente fuerte", "Un púlsar de rayos gamma", "Un agujero blanco"], en: ["A type of quasar", "A neutron star with an extremely strong magnetic field", "A gamma-ray pulsar", "A white hole"] }, correctAnswer: { es: "Una estrella de neutrones con un campo magnético extremadamente fuerte", en: "A neutron star with an extremely strong magnetic field" } },
            { question: { es: "La 'Paradoja de Fermi' se pregunta sobre la aparente contradicción entre la alta probabilidad de... y la falta de evidencia.", en: "The 'Fermi Paradox' asks about the apparent contradiction between the high probability of... and the lack of evidence." }, options: { es: ["Viaje en el tiempo", "Vida extraterrestre", "Agujeros de gusano", "Universos paralelos"], en: ["Time travel", "Extraterrestrial life", "Wormholes", "Parallel universes"] }, correctAnswer: { es: "Vida extraterrestre", en: "Extraterrestrial life" } },
            { question: { es: "¿Qué es la 'nanotecnología molecular'?", en: "What is 'molecular nanotechnology'?" }, options: { es: ["El estudio de moléculas pequeñas", "La construcción de máquinas a escala molecular", "La creación de nanomateriales", "La manipulación de átomos individuales"], en: ["The study of small molecules", "The construction of machines at the molecular scale", "The creation of nanomaterials", "The manipulation of individual atoms"] }, correctAnswer: { es: "La construcción de máquinas a escala molecular", en: "The construction of machines at the molecular scale" } }
        ]
    },
    {
        id: 27, title: "Nivel 27", passingScore: 1.0,
        questions: [
            { question: { es: "El 'horizonte cosmológico' es el límite del universo...", en: "The 'cosmological horizon' is the limit of the... universe." }, options: { es: ["Conocido", "Observable", "Existente", "Físico"], en: ["Known", "Observable", "Existing", "Physical"] }, correctAnswer: { es: "Observable", en: "Observable" } },
            { question: { es: "¿Qué es un 'axioma' en matemáticas y lógica?", en: "What is an 'axiom' in mathematics and logic?" }, options: { es: ["Una conjetura", "Una proposición considerada evidente y aceptada sin demostración", "Un teorema complejo", "Una contradicción"], en: ["A conjecture", "A proposition considered self-evident and accepted without proof", "A complex theorem", "A contradiction"] }, correctAnswer: { es: "Una proposición considerada evidente y aceptada sin demostración", en: "A proposition considered self-evident and accepted without proof" } },
            { question: { es: "El 'problema de la jerarquía' en física de partículas se refiere a la gran discrepancia entre... y la fuerza de gravedad.", en: "The 'hierarchy problem' in particle physics refers to the large discrepancy between... and the force of gravity." }, options: { es: ["La fuerza electromagnética", "La fuerza nuclear débil", "La fuerza nuclear fuerte", "La masa del bosón de Higgs"], en: ["The electromagnetic force", "The weak nuclear force", "The strong nuclear force", "The mass of the Higgs boson"] }, correctAnswer: { es: "La fuerza nuclear débil", en: "The weak nuclear force" } },
            { question: { es: "¿Qué es la 'radiación de Hawking'?", en: "What is 'Hawking radiation'?" }, options: { es: ["Radiación emitida por estrellas de neutrones", "Radiación teórica emitida por los agujeros negros", "El fondo cósmico de microondas", "Una forma de radiación gamma"], en: ["Radiation emitted by neutron stars", "Theoretical radiation emitted by black holes", "The cosmic microwave background", "A form of gamma radiation"] }, correctAnswer: { es: "Radiación teórica emitida por los agujeros negros", en: "Theoretical radiation emitted by black holes" } },
            { question: { es: "La 'hipótesis del universo holográfico' sugiere que nuestro universo tridimensional podría ser una proyección de información en una superficie...", en: "The 'holographic universe hypothesis' suggests that our three-dimensional universe could be a projection of information on a... surface." }, options: { es: ["Esférica", "Plana", "Bidimensional", "Multidimensional"], en: ["Spherical", "Flat", "Two-dimensional", "Multidimensional"] }, correctAnswer: { es: "Bidimensional", en: "Two-dimensional" } }
        ]
    },
    {
        id: 28, title: "Nivel 28", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es un 'fluido no newtoniano'?", en: "What is a 'non-Newtonian fluid'?" }, options: { es: ["Un fluido que no fluye", "Un fluido cuya viscosidad cambia bajo estrés", "Un fluido superdenso", "Un fluido gaseoso"], en: ["A fluid that does not flow", "A fluid whose viscosity changes under stress", "A superdense fluid", "A gaseous fluid"] }, correctAnswer: { es: "Un fluido cuya viscosidad cambia bajo estrés", en: "A fluid whose viscosity changes under stress" } },
            { question: { es: "La 'paradoja de Olbers' pregunta por qué el cielo nocturno es...", en: "Olbers' paradox asks why the night sky is..." }, options: { es: ["Oscuro", "Brillante", "Lleno de estrellas", "Azul"], en: ["Dark", "Bright", "Full of stars", "Blue"] }, correctAnswer: { es: "Oscuro", en: "Dark" } },
            { question: { es: "¿Qué son los 'puntos cuánticos'?", en: "What are 'quantum dots'?" }, options: { es: ["Partículas subatómicas", "Defectos en cristales", "Nanocristales semiconductores con propiedades ópticas", "Un estado de la materia"], en: ["Subatomic particles", "Defects in crystals", "Semiconductor nanocrystals with optical properties", "A state of matter"] }, correctAnswer: { es: "Nanocristales semiconductores con propiedades ópticas", en: "Semiconductor nanocrystals with optical properties" } },
            { question: { es: "El 'problema de los tres cuerpos' en física se refiere a la dificultad de predecir el movimiento de tres cuerpos bajo la influencia de...", en: "The 'three-body problem' in physics refers to the difficulty of predicting the motion of three bodies under the influence of..." }, options: { es: ["El magnetismo", "La gravedad mutua", "La fricción", "La presión"], en: ["Magnetism", "Mutual gravity", "Friction", "Pressure"] }, correctAnswer: { es: "La gravedad mutua", en: "Mutual gravity" } },
            { question: { es: "¿Qué es la 'espintrónica'?", en: "What is 'spintronics'?" }, options: { es: ["Electrónica basada en el espín del electrón", "Electrónica a escala atómica", "Computación óptica", "Electrónica flexible"], en: ["Electronics based on the electron's spin", "Electronics at the atomic scale", "Optical computing", "Flexible electronics"] }, correctAnswer: { es: "Electrónica basada en el espín del electrón", en: "Electronics based on the electron's spin" } }
        ]
    },
    {
        id: 29, title: "Nivel 29", passingScore: 1.0,
        questions: [
            { question: { es: "La 'escala de Kardashev' mide el nivel de avance tecnológico de una civilización basado en...", en: "The 'Kardashev scale' measures a civilization's level of technological advancement based on..." }, options: { es: ["Su capacidad de viaje espacial", "Su consumo de energía", "Su poder computacional", "Su población"], en: ["Its space travel capability", "Its energy consumption", "Its computational power", "Its population"] }, correctAnswer: { es: "Su consumo de energía", en: "Its energy consumption" } },
            { question: { es: "¿Qué es la 'levitación acústica'?", en: "What is 'acoustic levitation'?" }, options: { es: ["Levitación magnética", "Uso de ondas sonoras para hacer levitar objetos", "Un truco de magia", "Un fenómeno antigravitacional"], en: ["Magnetic levitation", "Using sound waves to levitate objects", "A magic trick", "An anti-gravity phenomenon"] }, correctAnswer: { es: "Uso de ondas sonoras para hacer levitar objetos", en: "Using sound waves to levitate objects" } },
            { question: { es: "El 'vacío cuántico' no está realmente vacío, sino lleno de...", en: "The 'quantum vacuum' is not truly empty, but filled with..." }, options: { es: ["Materia oscura", "Energía oscura", "Partículas virtuales que aparecen y desaparecen", "Neutrinos"], en: ["Dark matter", "Dark energy", "Virtual particles that appear and disappear", "Neutrinos"] }, correctAnswer: { es: "Partículas virtuales que aparecen y desaparecen", en: "Virtual particles that appear and disappear" } },
            { question: { es: "La 'astrobiología' es el estudio de...", en: "Astrobiology is the study of..." }, options: { es: ["La historia de la astronomía", "La vida en otros planetas", "La composición de las estrellas", "Los agujeros negros"], en: ["The history of astronomy", "Life on other planets", "The composition of stars", "Black holes"] }, correctAnswer: { es: "La vida en otros planetas", en: "Life on other planets" } },
            { question: { es: "¿Qué es un 'metamaterial'?", en: "What is a 'metamaterial'?" }, options: { es: ["Un material natural", "Un material con propiedades no encontradas en la naturaleza", "Un superaleación", "Un polímero avanzado"], en: ["A natural material", "A material with properties not found in nature", "A superalloy", "An advanced polymer"] }, correctAnswer: { es: "Un material con propiedades no encontradas en la naturaleza", en: "A material with properties not found in nature" } }
        ]
    },
    {
        id: 30, title: "Nivel 30", passingScore: 1.0,
        questions: [
            { question: { es: "¿Qué es la 'hipótesis de simulación'?", en: "What is the 'simulation hypothesis'?" }, options: { es: ["Una simulación por computadora", "La idea de que nuestra realidad es una simulación artificial", "Un modelo climático", "Una teoría económica"], en: ["A computer simulation", "The idea that our reality is an artificial simulation", "A climate model", "An economic theory"] }, correctAnswer: { es: "La idea de que nuestra realidad es una simulación artificial", en: "The idea that our reality is an artificial simulation" } },
            { question: { es: "El 'problema del horizonte' en cosmología se refiere a por qué diferentes regiones del universo...", en: "The 'horizon problem' in cosmology refers to why different regions of the universe..." }, options: { es: ["Se están alejando", "Tienen la misma temperatura", "Tienen diferentes leyes físicas", "Están vacías"], en: ["Are moving apart", "Have the same temperature", "Have different physical laws", "Are empty"] }, correctAnswer: { es: "Tienen la misma temperatura", en: "Have the same temperature" } },
            { question: { es: "¿Qué son los 'anillos de Einstein'?", en: "What are 'Einstein rings'?" }, options: { es: ["Joyas usadas por Einstein", "La deformación de la luz de una fuente distante en un anillo por una lente gravitacional", "Órbitas planetarias", "Una teoría de la relatividad"], en: ["Jewelry worn by Einstein", "The deformation of light from a distant source into a ring by a gravitational lens", "Planetary orbits", "A theory of relativity"] }, correctAnswer: { es: "La deformación de la luz de una fuente distante en un anillo por una lente gravitacional", en: "The deformation of light from a distant source into a ring by a gravitational lens" } },
            { question: { es: "La 'muerte térmica del universo' es un escenario final donde el universo alcanza un estado de...", en: "The 'heat death of the universe' is an end scenario where the universe reaches a state of..." }, options: { es: ["Frío absoluto", "Máxima entropía", "Colapso total", "Expansión infinita"], en: ["Absolute cold", "Maximum entropy", "Total collapse", "Infinite expansion"] }, correctAnswer: { es: "Máxima entropía", en: "Maximum entropy" } },
            { question: { es: "¿Qué es un 'ordenador de ADN'?", en: "What is a 'DNA computer'?" }, options: { es: ["Un ordenador que secuencia ADN", "Un ordenador que utiliza ADN para almacenar y procesar datos", "Un simulador biológico", "Una inteligencia artificial"], en: ["A computer that sequences DNA", "A computer that uses DNA to store and process data", "A biological simulator", "An artificial intelligence"] }, correctAnswer: { es: "Un ordenador que utiliza ADN para almacenar y procesar datos", en: "A computer that uses DNA to store and process data" } }
        ]
    }
];